name: namazvaktim
description: "A new Flutter project."


version: 2.0.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  hijri_date: ^1.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  location: ^8.0.1
  geolocator: ^14.0.2
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    # BIRINCI FONT
    - family: MyFont
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    # IKINCI FONT
    - family: MyFont2
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
